name: Focus Area Proposal
description: Proposal for an Interop 2024 Focus Area
labels: focus-area-proposal
body:
- type: markdown
  attributes:
    value: |
      Thanks for making an Interop 2024 Proposal

      Please see the [Interop 2024 README](https://github.com/web-platform-tests/interop/blob/main/2024/README.md) for the timeline and what to expect from the process.

      If this feature is widely implemented, but lacks a high quality specification or tests, an [Investigation Effort](https://github.com/web-platform-tests/interop/issues/new?template=investigation-effort-proposal.yml) may be more appropriate.
- type: markdown
  attributes:
    value: "## Proposal Details"
- type: textarea
  attributes:
    label: Description
    description: Brief description of the feature. Try to be clear about what parts of the feature are included and not.
  validations:
    required: true
- type: input
  attributes:
    label: Specification
    description: |
      Specification for the feature. The feature must defined by a standards-track specification from one of the following organizations:

      - [IETF](https://www.ietf.org/) (Standard Track)
      - [Khronos Group](https://www.khronos.org/)
      - [TC39](https://tc39.es/) (Stage 2+)
      - [W3C](https://www.w3.org/) (Recommendation Track)
      - [WHATWG](https://whatwg.org/)
  validations:
    required: true
- type: textarea
  attributes:
    label: Open Issues
    description: |
      Links to any open standards issues that affect the proposal.
- type: textarea
  attributes:
    label: Tests
    description: |
      Tests for the feature in web-platform-tests on [wpt.fyi](https://wpt.fyi/).

      These are the tests that will be used to score progress in this Focus Area. If the tests are not yet ready, link to evidence of the tests being worked on (e.g. a PR in the web-platform-tests repository or an issue in a vendor bug tracker).
- type: markdown
  attributes:
    value: "## Supporting Evidence

      The following fields are for collecting data to assess the likely impact on authors and users of improving interoperability of the proposed feature. It is not required to fill in all (or any) fields, but proposals with stronger supporting evidence are more likely to be selected."
- type: checkboxes
  attributes:
    label: Current Implementations
    description: |
      Which major browser engines already implement the feature?
    options:
      - label: Blink
      - label: Gecko
      - label: WebKit
- type: textarea
  attributes:
    label: Standards Positions
    description: |
      Links to [Gecko](https://mozilla.github.io/standards-positions/) or [WebKit](https://webkit.org/standards-positions/) Standards Positions, or Intent to Prototype / Ship emails for the feature.
- type: textarea
  attributes:
    label: Browser bug reports
    description: |
      Browser bugs or browser bug statistics, for example, [Chromium](https://bugs.chromium.org/), [Gecko](https://bugzilla.mozilla.org/), or [WebKit](https://bugs.webkit.org/).
- type: textarea
  attributes:
    label: Developer discussions
    description: |
      Examples of developers running into the lack of this feature, or problems with the feature, on sites like Stack Overflow.
- type: textarea
  attributes:
    label: Polls & Surveys
    description: |
      Developer feedback surveys referencing this feature e.g. for example, MDN surveys, [State of CSS](https://stateofcss.com/) or [State of JavaScript](https://stateofjs.com/en-us/).
- type: textarea
  attributes:
    label: Existing Usage
    description: |
      Evidence of existing usage of the feature e.g. [Chrome use counters](https://www.chromestatus.com/metrics/feature/popularity) or [HTTP Archive](https://httparchive.org/), or links to libraries or other code trying to use the feature.
- type: textarea
  attributes:
    label: Workarounds
    description: |
      Links to code that's trying to work around the absence of this feature e.g. polyfills.
- type: textarea
  attributes:
    label: Accessibility Impact
    description: |
      Information about the impact of the feature on the accessilbility properties of the web platform, if any.
- type: textarea
  attributes:
    label: Privacy Impact
    description: |
      Information about the impact of the feature on the privacy properties of the web platform, if any.
- type: textarea
  attributes:
    label: Other
    description: |
      Any other relevant information that will help assess the impact of making the feature more interoperable.
