name: Focus Area Proposal
description: Proposal for an Interop 2023 Focus Area
labels: focus-area-proposal
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to make a proposal for Interop 2023!

      Please see the [Interop 2023 README](https://github.com/web-platform-tests/interop/blob/main/2023/README.md) for the timeline and what to expect from the process.

      If this feature is widely implemented, but lacks a high quality specification or tests, an [Investigation Effort](https://github.com/web-platform-tests/interop/issues/new?template=investigation-effort-proposal.yml) may be more appropriate.
- type: textarea
  attributes:
    label: Description
    description: Brief description of the feature. Try to be clear about what parts of the feature are included and not.
- type: textarea
  attributes:
    label: Rationale
    description: |
      Reasons for including the feature. This should primarily be about web developer and/or end user impact of improving interoperability of this feature. A few dimensions to consider are:

      - Web developer sentiment from polls or surveys, for example, [MDN surveys](https://insights.developer.mozilla.org/) or [State of CSS](https://stateofcss.com/).
      - Examples of sites or libraries working around a missing feature or browser bug.
      - Browser bugs or browser bug statistics, for example, [Chromium](https://bugs.chromium.org/), [Gecko](https://bugzilla.mozilla.org/),  or [WebKit](https://bugs.webkit.org/).
      - Current usage of the feature, for example, [Chrome use counters](https://www.chromestatus.com/metrics/feature/popularity) or [HTTP Archive](https://httparchive.org/).
- type: textarea
  attributes:
    label: Specification
    description: |
      Specification for the feature. The feature should be defined by a standards-track specification from the following organizations:

      - [IETF](https://www.ietf.org/) (Standard Track)
      - [Khronos Group](https://www.khronos.org/)
      - [TC39](https://tc39.es/) (Stage 2+)
      - [W3C](https://www.w3.org/) (Recommendation Track)
      - [WHATWG](https://whatwg.org/)
- type: textarea
  attributes:
    label: Tests
    description: |
      Tests for the feature in web-platform-tests on [wpt.fyi](https://wpt.fyi/), or in Test262 on [test262.report](https://test262.report/).

      These are the tests that will be used to score progress in this Focus Area.
