name: Investigation Effort Proposal
description: Proposal for an Interop 2024 Investigation Effort
labels: investigation-effort-proposal
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to make a proposal for Interop 2024!

      Please see the [Interop 2024 README](https://github.com/web-platform-tests/interop/blob/main/2024/README.md) for the timeline and what to expect from the process.

      **Please make sure you're using the right proposal template!** If this feature has a high quality specification and tests, submit a [Focus Area](https://github.com/web-platform-tests/interop/issues/new?template=focus-area-proposal.yml) proposal instead.
- type: textarea
  attributes:
    label: Description
    description: Brief description of the feature. Try to be clear about what parts of the feature are included and not.
- type: textarea
  attributes:
    label: Rationale
    description: |
      Reasons for including the feature. A few dimensions to consider are:

      - Web developer sentiment from polls or surveys, for example, [MDN surveys](https://insights.developer.mozilla.org/) or [State of CSS](https://stateofcss.com/).
      - Examples of sites or libraries working around a missing feature or browser bug.
      - Browser bugs or browser bug statistics, for example, [Chromium](https://bugs.chromium.org/), [Gecko](https://bugzilla.mozilla.org/),  or [WebKit](https://bugs.webkit.org/).
      - Current usage of the feature, for example, [Chrome use counters](https://www.chromestatus.com/metrics/feature/popularity) or [HTTP Archive](https://httparchive.org/).
- type: textarea
  attributes:
    label: Investigation Roadmap
    description: |
      Please describe the steps necessary to get this feature to a state of high quality specification and tests. Link to existing spec and tests, and describe what needs to be done, ideally as a set of distinct tasks. If there are open-ended questions about the behavior that require investigation, try to still capture this as a set of tasks, such as "test existing behavior", "update specification", and "update tests".

      Any standards work must be done in the appropriate standards group, and those doing the work need to join that group. Interop 2024 is not a venue for specifying new features.
