name: labels
on:
  # Trigger every Monday morning, or manually.
  schedule:
    - cron: 55 5 * * 1
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: python -m pip install requests
    - name: Update labels
      run: python labels/labels.py
    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        title: "Update labels/"
        branch: actions/update-labels
